# Generated by Django 3.0.3 on 2021-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sroll', models.PositiveIntegerField()),
                ('smarks', models.FloatField()),
            ],
        ),
    ]
